openapi: 3.0.0
paths:
  /bcrypt/generate-hash:
    post:
      summary: Bcrypt Generate Hash
      operationId: api.bcrypt.generate_hash
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
                    description: パスワード
                  hash:
                    type: string
                    description: ハッシュ化したパスワード
                required:
                  - password
                  - hash
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: パスワード
                cost:
                  type: integer
                  default: 10
                  format: int32
                  minimum: 4
                  maximum: 10
                  description: ストレッチング回数
                version:
                  type: string
                  enum:
                    - 2a
                    - 2b
                  default: 2a
                  description: bcryptアルゴリズム
              required:
                - password
            examples:
              example:
                value:
                  password: Passw0rd
                  cost: 10
                  version: 2a
        description: ''
      description: パスワードハッシュ化を行うAPI
      tags:
        - bcrypt
    parameters: []
  /bcrypt/check-password:
    post:
      summary: Bcrypt Check Password
      operationId: api.bcrypt.check_password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: パスワードとハッシュ化したパスワードのチェック結果
                  password:
                    type: string
                    description: パスワード
                  hash:
                    type: string
                    description: ハッシュ化したパスワード
                required:
                  - result
                  - password
                  - hash
      description: パスワードとパスワードハッシュのチェックを行うAPI
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hash:
                  type: string
                  description: ハッシュ化したパスワード
                password:
                  type: string
                  description: パスワード
              required:
                - hash
                - password
            examples:
              example:
                value:
                  hash: $2a$10$UrC0NWxz.FHzGLrIp5PMcesTzs9YD6qSPw8yy4ZupM3YeoEswt4sq
                  password: Passw0rd
      tags:
        - bcrypt
    parameters: []
  /html/escape:
    post:
      summary: Html escape
      operationId: api.html.escape
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: 置換前の文字列
                  result:
                    type: string
                    description: 置換後の文字列
      tags:
        - html
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                string:
                  type: string
              required:
                - string
            examples:
              example:
                value:
                  string: ''' & " < >'
      description: ''' & " <> を実体参照に置換するAPI'
  /html/unescape:
    post:
      summary: Html unescape
      operationId: api.html.unescape
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: 置換前の文字列
                  result:
                    type: string
                    description: 置換後の文字列
      tags:
        - html
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                string:
                  type: string
              required:
                - string
            examples:
              example:
                value:
                  string: '&#x27; &amp; &quot; &lt; &gt;'
      description: 実体参照を文字列に置換するAPI
  /url/encode:
    post:
      summary: Url encode
      operationId: api.url.encode
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: エンコード前の文字列
                  result:
                    type: string
                    description: エンコード後の文字列
          headers: {}
      description: 文字列をURLエンコードするAPI
      tags:
        - url
  /url/decode:
    post:
      summary: Url decode
      operationId: api.url.decode
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: デコード前の文字列
                  result:
                    type: string
                    description: デコード後の文字列
          headers: {}
      tags:
        - url
      description: 文字列をURLデコードするAPI
components:
  schemas: {}
  securitySchemes: {}
info:
  title: Convert API
  description: 変換API
  version: '1.0'
  contact:
    name: ot-nemoto
    url: 'https://github.com/ot-nemoto/convert-api/issues'
    email: nemoto@opentone.co.jp
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000/api/v1'
tags:
  - name: bcrypt
    description: bcrypt generate-hash / check-password
  - name: html
    description: html escape / unescape
  - name: url
    description: url encode / decode
