openapi: 3.0.0
paths:
  /generate-hash:
    post:
      summary: Generate Hash
      operationId: api.bcrypt.generate_hash
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
                    description: パスワード
                  hash:
                    type: string
                    description: ハッシュ化したパスワード
                required:
                  - password
                  - hash
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: パスワード
                cost:
                  type: integer
                  default: 10
                  format: int32
                  minimum: 4
                  maximum: 10
                  description: ストレッチング回数
                version:
                  type: string
                  enum:
                    - 2a
                    - 2b
                  default: 2a
                  description: bcryptアルゴリズム
              required:
                - password
            examples:
              example:
                value:
                  password: Passw0rd
                  cost: 10
                  version: 2a
        description: ''
      description: パスワードハッシュ化を行うAPI
    parameters: []
  /check-password:
    post:
      summary: Check Password
      operationId: api.bcrypt.check_password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: パスワードとハッシュ化したパスワードのチェック結果
                  password:
                    type: string
                    description: パスワード
                  hash:
                    type: string
                    description: ハッシュ化したパスワード
                required:
                  - result
                  - password
                  - hash
      description: パスワードとパスワードハッシュのチェックを行うAPI
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hash:
                  type: string
                  description: ハッシュ化したパスワード
                password:
                  type: string
                  description: パスワード
              required:
                - hash
                - password
            examples:
              example:
                value:
                  hash: $2a$10$UrC0NWxz.FHzGLrIp5PMcesTzs9YD6qSPw8yy4ZupM3YeoEswt4sq
                  password: Passw0rd
components:
  schemas: {}
  securitySchemes: {}
info:
  title: Convert API
  description: 変換API
  version: '1.0'
  contact:
    name: ot-nemoto
    url: 'https://github.com/ot-nemoto/bcrypt-api/issues'
    email: nemoto@opentone.co.jp
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000/api/v1/convert'
